site_name: liu0707262021's blog
site_url: https://liu0707262021.github.io/my-blog-demo/
nav:
  - 首页: index.md
  - 第一篇: first-article.md
theme:
  name: readthedocs
extra_css:
  - assets/css/hide-footer.css